[package]
name = "cliprelay-client"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arboard.workspace = true
clap.workspace = true
cliprelay-core = { path = "../cliprelay-core" }
eframe.workspace = true
egui.workspace = true
futures.workspace = true
hex.workspace = true
serde.workspace = true
sha2.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
